#
# Automagically generated by Approximatrix Simply Fortran 2.26
#
FC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gfortran.exe"
CC="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\gcc.exe"
AR="C:\Program Files (x86)\Simply Fortran 2\mingw-w64\bin\ar.exe"
WRC="C:\PROGRA~2\SIMPLY~1\MINGW-~1\bin\windres.exe"
RM=rm -f

IDIR=

LDIR=-LC:/PROGRA~2/SIMPLY~1/MINGW-~1/lib/ 


OPTFLAGS= -g

SPECIALFLAGS=-m32 $(IDIR)

RCFLAGS=-O coff -F pe-i386

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build\read.o": ".\read.for"
	@echo Compiling .\read.for
	@$(FC) -c -o "build\read.o" $(FFLAGS) ".\read.for"

"build\READ_GDR_PAR.o": ".\READ_GDR_PAR.for"
	@echo Compiling .\READ_GDR_PAR.for
	@$(FC) -c -o "build\READ_GDR_PAR.o" $(FFLAGS) ".\READ_GDR_PAR.for"

clean: .SYMBOLIC
	@echo Deleting build\read.o and related files
	@$(RM) "build\read.o"
	@echo Deleting build\READ_GDR_PAR.o and related files
	@$(RM) "build\READ_GDR_PAR.o"
	@echo Deleting target.exe
	@$(RM) "target.exe"

"target.exe":  "build\read.o" "build\READ_GDR_PAR.o" "build\project.prj.target"
	@echo Generating target.exe
	@$(FC) -o "target.exe" -static -m32 "build\read.o" "build\READ_GDR_PAR.o" $(LDIR) $(PRJ_LFLAGS)

all: "target.exe" .SYMBOLIC

